jitpcb \
  lib/components.stanza \
  lib/parts.stanza \
  lib/peripherals.stanza \
  lib/rules.stanza \
  lib/stackups.stanza \
  lib/footprints.stanza \
  lib/interfaces.stanza \
  lib/modules.stanza \
  lib/symbols.stanza \
  src/ir/ir-lower.stanza \
  src/ir/part-solver.stanza \
  src/ir/ir-gen.stanza \
  src/ir/ir-utils.stanza \
  src/connectorizer/spec.stanza \
  src/connectorizer/connectors.stanza \
  src/connectorizer/gen.stanza \
  -o connectorizer
